apiVersion: v1
kind: Service
metadata:
  name: skyscanner-flights-discovery
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: skyscanner-flights-discovery
    tier: backend

